### ISSUE TITLE
Makefile parsing and interpolation speed improvement

### ISSUE THREAD

**Issue by da-x** [buildsome/buildsome#70]
#### Introduction
Presently, the time it takes for Buildsome to parse and do its string interpolation on the tree of makefile definitions is high - around 20 seconds in our project. `gmake` does the same parsing and interpolation work in considerably less time.

To partly address this, Buildsome caches the parsing and interpolation in order to reduce it to the few seconds range. However even a small edit takes a considerable developer time toll.
Work has previously began to decrease that time by implementing an efficient parser and interpolation, and it showed promise. However it is incomplete. This issue is for the completion of the task.
The implementation is almost done.

@sinelaw @Peaker 

## Status

[Done](https://github.com/da-x/buildsome/tree/new-mk-parser).

### Nice to have

* Optimize the BuildMaps

**Comment by da-x** [comment]
Done order-only inputs.

**Comment by da-x** [comment]
Done: error reporting - all parse errors now include filename/line/col.

**Comment by da-x** [comment]
Done: Building an RPM of Buildsome using Stack.

Several devs experiment working with it in their environments.

**Comment by da-x** [comment]
Hey, you want to take the new-mk-parser branch and clean it up? We have been using it for awhile quite successfully.

**Comment by ElastiLotem** [comment]
Cool, will see if I have time to do that...

Does it work for rules named "endif" btw? :)

On Sat, Jun 18, 2016 at 8:28 AM, Dan Aloni <notifications@github.com> wrote:

> Hey, you want to take the new-mk-parser branch and clean it up? We have
> been using it for awhile quite successfully.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ElastiLotem/buildsome/issues/70#issuecomment-226923226>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGJGI3ee9ncHr1Ezf6LKHCGa9KY6qJ5Dks5qM4H5gaJpZM4IUBC7>
> .
>



-- 
Eyal

**Comment by da-x** [comment]
Yes, see 10efc5c615a5877e9a59df867b128b824e385cec
