### ISSUE TITLE
Drop caching from roadmap, look at sccache instead

### ISSUE THREAD

**Issue by mqudsi** [buildsome/buildsome#89]
The sscache distributed/cloud ccache utility from Mozilla targets pretty much everything buildsome's future caching plans encompasses. I suggest you look at it and see if it is still worth re-inventing: https://github.com/mozilla/sccache

**Comment by da-x** [comment]
sscache is compiler-specific, dealing with only specific types of build targets; buildsome will cache all build targets including the intermediate ones. Therefore, we should not drop this feature from roadmap.
